"""Replace the @@EQnn@@ placeholders written by make_docx.js with native Word
(OMML) equation objects, so the equations stay editable in Word's equation editor.

The OMML is generated by pandoc from equations.tex.md — pandoc's LaTeX-to-OMML
conversion is the reference implementation for this and round-trips cleanly in
Word. Each placeholder run is replaced by the corresponding inline <m:oMath>
element; the surrounding paragraph (tab stops, equation number) is left alone.

Usage:  node make_docx.js && python3 insert_equations.py
"""
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

DOCX = Path("5.56_interior_ballistics.docx")
SRC = Path("equations.tex.md")
TMP = Path("_eq_omml.docx")

# ---------------------------------------------------------------- 1. pandoc
subprocess.run(["pandoc", str(SRC), "-o", str(TMP)], check=True)
xml = zipfile.ZipFile(TMP).read("word/document.xml").decode("utf8")
TMP.unlink()

def fix_schema_order(x):
    """Pandoc emits two element orderings the OOXML schema rejects. Word tolerates
    them, but the file should validate, so they are corrected here.

    * CT_Dpr requires begChr, sepChr, endChr, grow - pandoc writes endChr first.
    * CT_MathRPr makes <m:nor/> and <m:sty/> mutually exclusive - pandoc writes
      both; <m:nor/> alone gives the same upright rendering.
    """
    x = re.sub(r"(<m:begChr[^>]*/>)\s*(<m:endChr[^>]*/>)\s*(<m:sepChr[^>]*/>)",
               r"\1\3\2", x)
    x = re.sub(r"(<m:nor\s*/>)\s*<m:sty[^>]*/>", r"\1", x)
    return x


blocks = re.findall(r"<m:oMathPara>.*?</m:oMathPara>", xml, re.S)
omml = []
for b in blocks:
    m = re.search(r"<m:oMath>.*?</m:oMath>", b, re.S)
    if m:
        omml.append(fix_schema_order(m.group(0)))
print(f"pandoc produced {len(omml)} OMML equations")

# ---------------------------------------------------------------- 2. splice
tmpdir = Path("_unpacked")
if tmpdir.exists():
    shutil.rmtree(tmpdir)
with zipfile.ZipFile(DOCX) as z:
    z.extractall(tmpdir)

doc = (tmpdir / "word/document.xml").read_text(encoding="utf8")
missing = []
for i, eq in enumerate(omml, 1):
    tag = f"@@EQ{i:02d}@@"
    # the placeholder is a single run containing only the marker
    pat = re.compile(r"<w:r>(?:(?!</w:r>).)*?" + re.escape(tag) + r"</w:t></w:r>", re.S)
    doc, n = pat.subn(lambda _m, e=eq: e, doc, count=1)
    if n != 1:
        missing.append(tag)
if missing:
    sys.exit(f"ERROR: placeholders not replaced: {missing}")
left = re.findall(r"@@EQ\d\d@@", doc)
if left:
    sys.exit(f"ERROR: leftover placeholders: {left}")

(tmpdir / "word/document.xml").write_text(doc, encoding="utf8")

# ---------------------------------------------------------------- 3. rezip
out = Path("5.56_interior_ballistics.docx")
if out.exists():
    out.unlink()
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
    for f in sorted(tmpdir.rglob("*")):
        if f.is_file():
            z.write(f, f.relative_to(tmpdir).as_posix())
shutil.rmtree(tmpdir)

print(f"wrote {out} with {len(omml)} native OMML equations "
      f"({out.stat().st_size/1024:.0f} kB)")
